# Generated by Django 4.2.24 on 2025-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0028_enhance_formula_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsdata',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text="Custom fields - Add any column dynamically! Example: {'my_custom_calc': 123.45, 'special_value': 99.9}", null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='category',
            field=models.CharField(choices=[('renewable', 'Renewable Energy'), ('verbrauch', 'Energy Consumption'), ('landuse', 'Land Use'), ('bilanz', 'Energy Balance'), ('ws', 'Energy Storage (WS)'), ('other', 'Other')], default='renewable', help_text='Category for organizing formulas', max_length=50),
        ),
    ]
