# Generated by Django 4.2.24 on 2025-12-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0029_add_custom_fields_to_ws'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDisplayName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(choices=[('renewable', 'Renewable Energy'), ('verbrauch', 'Energy Consumption'), ('landuse', 'Land Use'), ('bilanz', 'Energy Balance'), ('ws', 'Energy Storage (WS)'), ('ws_constant', 'WS Constants'), ('bilanz_constant', 'Bilanz Constants'), ('other', 'Other')], help_text='Internal category code (hardcoded in backend)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown in UI (change freely!)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide in UI')),
            ],
            options={
                'verbose_name': 'Category Display Name',
                'verbose_name_plural': 'Category Display Names',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.AlterField(
            model_name='formula',
            name='category',
            field=models.CharField(choices=[('renewable', 'Renewable Energy'), ('verbrauch', 'Energy Consumption'), ('landuse', 'Land Use'), ('bilanz', 'Energy Balance'), ('ws', 'Energy Storage (WS)'), ('ws_constant', 'WS Constants'), ('bilanz_constant', 'Bilanz Constants'), ('other', 'Other')], default='renewable', help_text='Category for organizing formulas (use CategoryDisplayName to change display)', max_length=50),
        ),
    ]
