# Generated by Django 6.0 on 2025-12-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0030_add_category_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='formula_type',
            field=models.CharField(choices=[('status', 'Status (Current Value)'), ('ziel', 'Ziel/Target (Target Value)')], default='status', help_text="Select 'Status' for current value formula, 'Ziel' for target value formula. System will add _ziel/_target suffix automatically.", max_length=20),
        ),
        migrations.AlterField(
            model_name='formulavariable',
            name='source_type',
            field=models.CharField(choices=[('landuse_status', 'LandUse status_ha'), ('landuse_target', 'LandUse target_ha'), ('renewable_status', 'RenewableData status_value (self)'), ('renewable_target', 'RenewableData target_value (self)'), ('renewable_code_status', '➜ Other RenewableData code - status'), ('renewable_code_target', '➜ Other RenewableData code - target'), ('verbrauch_status', 'VerbrauchData status (self)'), ('verbrauch_ziel', 'VerbrauchData ziel (self)'), ('verbrauch_code_status', '➜ Other VerbrauchData code - status'), ('verbrauch_code_ziel', '➜ Other VerbrauchData code - ziel'), ('literal', 'Literal number')], help_text='Type of data source', max_length=30),
        ),
    ]
