# Generated by Django 4.2.24 on 2025-12-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0031_formula_formula_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSFormulaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(help_text='Exact field name in WSData model (e.g., stromverbr, windstrom, ladezust_burtto)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name shown in admin (e.g., 'Stromverbrauch', 'Windstrom')", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of what this column represents and how it's calculated")),
                ('formula_day_1', models.TextField(blank=True, help_text="Formula for Day 1 ONLY (first day - no 'day_prev' available). Example: verbrauch_promille * stromverbr_366")),
                ('formula_days_2_365', models.TextField(blank=True, help_text="Pattern for Days 2-365. Use 'day_prev.column' for previous day. Example: day_prev.ladezust_burtto + row.einspeich - row.ausspeich")),
                ('formula_row_366', models.TextField(blank=True, help_text="Annual summary formula. Use sums['sum_column'] for totals. Example: sums['sum_stromverbr']")),
                ('formula_row_367', models.TextField(blank=True, help_text='Reference row for storage calculations. Example: MIN(0, day_1.ladezust_burtto)')),
                ('formula_row_368', models.TextField(blank=True, help_text='Additional reference row (optional). Example: day_366.column / 365')),
                ('custom_row_formulas', models.JSONField(blank=True, default=dict, help_text="JSON for additional rows: {'369': 'formula', '370': 'formula'}")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are ignored during calculation')),
                ('priority', models.IntegerField(default=100, help_text='Calculation order: lower numbers calculated first. Use this for columns that depend on other columns.')),
                ('depends_on', models.CharField(blank=True, help_text='Comma-separated list of column names this formula depends on (for documentation and validation)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WS Formula Template',
                'verbose_name_plural': 'WS Formula Templates',
                'ordering': ['priority', 'column_name'],
            },
        ),
    ]
