# Generated by Django 4.2.24 on 2025-12-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0032_add_ws_formula_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='ws_row_type',
            field=models.CharField(blank=True, choices=[('all', 'All Rows (Default)'), ('day_1', 'Day 1 Only'), ('days_2_365', 'Days 2-365 (Pattern)'), ('row_366', 'Row 366 (Annual Summary)'), ('row_367', 'Row 367 (Reference)'), ('row_368', 'Row 368+')], default='all', help_text="🔧 FOR WS FORMULAS ONLY: Which rows this formula applies to. Use 'Days 2-365' for patterns with day_prev references.", max_length=20),
        ),
    ]
