# Generated by Django 4.2.24 on 2026-01-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0033_add_ws_row_type_to_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbrauchdata',
            name='is_user_editable',
            field=models.BooleanField(default=False, help_text="If checked, users can edit this value's user_percent in the frontend"),
        ),
    ]
