# Generated by Django 4.2.24 on 2026-01-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0034_verbrauchdata_is_user_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbrauchdata',
            name='is_user_editable',
        ),
        migrations.AddField(
            model_name='verbrauchdata',
            name='user_editable',
            field=models.BooleanField(default=False),
        ),
    ]
