# Generated by Django 4.2.24 on 2026-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0035_remove_verbrauchdata_is_user_editable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulavariable',
            name='source_type',
            field=models.CharField(choices=[('landuse_status', 'LandUse status_ha'), ('landuse_target', 'LandUse target_ha'), ('renewable_status', 'RenewableData status_value (self)'), ('renewable_target', 'RenewableData target_value (self)'), ('renewable_code_status', '➜ Other RenewableData code - status'), ('renewable_code_target', '➜ Other RenewableData code - target'), ('verbrauch_status', 'VerbrauchData status (self)'), ('verbrauch_ziel', 'VerbrauchData ziel (self)'), ('verbrauch_code_status', '➜ Other VerbrauchData code - status'), ('verbrauch_code_ziel', '➜ Other VerbrauchData code - ziel'), ('ws_row_value', '➜ WSData current row column value'), ('ws_row_366', '➜ WSData row 366 reference value'), ('ws_sum', '➜ WSData sum of column (days 1-365)'), ('ws_day_prev', '➜ WSData previous day column value'), ('literal', 'Literal number')], help_text='Type of data source', max_length=30),
        ),
    ]
