# Generated by Django 4.2.24 on 2026-02-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0036_add_ws_formula_variable_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='increase_limit_baseline_percent',
            field=models.FloatField(blank=True, help_text='Fixed baseline percent for max-increase validation (+LANDUSE_MAX_INCREASE_PERCENT points).', null=True),
        ),
    ]
