# Generated by Django 4.2.24 on 2026-02-19 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0038_balancejob'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verbrauchdata',
            name='simulator_v_code_af60ee_idx',
        ),
        migrations.AddField(
            model_name='landuse',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landuse_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renewabledata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewable_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verbrauchdata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verbrauch_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wsdata',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ws_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verbrauchdata',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='landuse',
            index=models.Index(fields=['owner', 'code'], name='simulator_l_owner_i_babf34_idx'),
        ),
        migrations.AddIndex(
            model_name='renewabledata',
            index=models.Index(fields=['owner', 'category'], name='simulator_r_owner_i_e45612_idx'),
        ),
        migrations.AddIndex(
            model_name='renewabledata',
            index=models.Index(fields=['owner', 'code'], name='simulator_r_owner_i_a214f3_idx'),
        ),
        migrations.AddIndex(
            model_name='verbrauchdata',
            index=models.Index(fields=['owner', 'code'], name='simulator_v_owner_i_42d8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='wsdata',
            index=models.Index(fields=['owner', 'tag_im_jahr'], name='simulator_w_owner_i_63c259_idx'),
        ),
        migrations.AddConstraint(
            model_name='landuse',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='landuse_owner_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='landuse',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('code',), name='landuse_global_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='renewabledata',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), fields=('owner', 'code'), name='renewable_owner_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='renewabledata',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False), ('owner__isnull', True), models.Q(('code', ''), _negated=True)), fields=('code',), name='renewable_global_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='verbrauchdata',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='verbrauch_owner_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='verbrauchdata',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('code',), name='verbrauch_global_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='wsdata',
            constraint=models.UniqueConstraint(fields=('owner', 'tag_im_jahr'), name='wsdata_owner_day_uniq'),
        ),
        migrations.AddConstraint(
            model_name='wsdata',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('tag_im_jahr',), name='wsdata_global_day_uniq'),
        ),
    ]
