# Generated by Django 4.2.24 on 2026-02-19 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0039_remove_verbrauchdata_simulator_v_code_af60ee_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['key'], name='simulator_b_key_c066b6_idx'), models.Index(fields=['owner', 'updated_at'], name='simulator_b_owner_i_e531e5_idx')],
            },
        ),
    ]
