# Generated by Django 4.2.24 on 2026-03-03

from django.db import migrations, models


def seed_default_ws365_formulas(apps, schema_editor):
    WS365Formula = apps.get_model("simulator", "WS365Formula")
    if WS365Formula.objects.exists():
        return

    defaults = [
        {
            "column_name": "stromverbrauch",
            "stage": "daily",
            "order": 10,
            "expression": "annual_demand * verbrauch_promille / 1000",
            "description": "Daily electricity demand from annual demand and verbrauch promille.",
        },
        {
            "column_name": "davon_raumw_korr",
            "stage": "daily",
            "order": 20,
            "expression": "raumw_korr_annual * heizung_abwaerm_promille / 365",
            "description": "Daily heating correction share.",
        },
        {
            "column_name": "stromverbr_raumw_korr",
            "stage": "daily",
            "order": 30,
            "expression": "stromverbrauch + davon_raumw_korr",
            "description": "Corrected daily electricity demand.",
        },
        {
            "column_name": "solar_strom",
            "stage": "daily",
            "order": 40,
            "expression": "ziel_912 * pct * solar_promille / 1000",
            "description": "Daily solar generation.",
        },
        {
            "column_name": "wind_strom",
            "stage": "daily",
            "order": 50,
            "expression": "ziel_911 * pct * wind_promille / 1000",
            "description": "Daily wind generation.",
        },
        {
            "column_name": "sonst_kraftw",
            "stage": "daily",
            "order": 60,
            "expression": "sonst_kraftw_daily",
            "description": "Constant daily other generation.",
        },
        {
            "column_name": "wind_solar_konstant",
            "stage": "daily",
            "order": 70,
            "expression": "solar_strom + wind_strom + sonst_kraftw",
            "description": "Total generation (wind + solar + constant).",
        },
        {
            "column_name": "direktverbr_strom",
            "stage": "daily",
            "order": 80,
            "expression": "MIN(wind_solar_konstant, stromverbr_raumw_korr)",
            "description": "Directly used electricity.",
        },
        {
            "column_name": "ueberschuss_strom",
            "stage": "daily",
            "order": 90,
            "expression": "IF(direktverbr_strom == stromverbr_raumw_korr, wind_solar_konstant - stromverbr_raumw_korr, 0)",
            "description": "Surplus electricity.",
        },
        {
            "column_name": "einspeich",
            "stage": "daily",
            "order": 100,
            "expression": "IF(stromverbr_raumw_korr > 0, IF((ueberschuss_strom / stromverbr_raumw_korr) <= 1, ueberschuss_strom * ETA_STROM_GAS, stromverbr_raumw_korr * ETA_STROM_GAS), 0)",
            "description": "Stored energy flow.",
        },
        {
            "column_name": "abregelung",
            "stage": "daily",
            "order": 110,
            "expression": "IF(stromverbr_raumw_korr > 0, IF((ueberschuss_strom / stromverbr_raumw_korr) <= 1, 0, ueberschuss_strom - einspeich / ETA_STROM_GAS), 0)",
            "description": "Curtailment due to surplus above storage threshold.",
        },
        {
            "column_name": "mangel_last",
            "stage": "daily",
            "order": 120,
            "expression": "stromverbr_raumw_korr - direktverbr_strom",
            "description": "Demand gap after direct consumption.",
        },
        {
            "column_name": "brennstoff_ausgleich",
            "stage": "daily",
            "order": 130,
            "expression": "brennstoff_factor * mangel_last",
            "description": "Fuel compensation using annual scaling factor.",
        },
        {
            "column_name": "speicher_ausgl_strom",
            "stage": "daily",
            "order": 140,
            "expression": "mangel_last - brennstoff_ausgleich",
            "description": "Storage compensation electricity.",
        },
        {
            "column_name": "ausspeich_rueckverstr",
            "stage": "daily",
            "order": 150,
            "expression": "speicher_ausgl_strom / ETA_GAS_STROM",
            "description": "Discharge back-conversion.",
        },
        {
            "column_name": "ausspeich_gas",
            "stage": "daily",
            "order": 160,
            "expression": "0",
            "description": "Gas discharge (currently fixed to 0).",
        },
        {
            "column_name": "ladezust_brutto",
            "stage": "daily",
            "order": 170,
            "expression": 'PREV("ladezust_brutto") + einspeich - ausspeich_rueckverstr - ausspeich_gas',
            "description": "Gross storage level (recursive by day).",
        },
        {
            "column_name": "selbstentl",
            "stage": "daily",
            "order": 180,
            "expression": "0",
            "description": "Self-discharge (currently fixed to 0).",
        },
        {
            "column_name": "ladezust_netto",
            "stage": "daily",
            "order": 190,
            "expression": 'PREV("ladezust_netto") + einspeich - ausspeich_rueckverstr - ausspeich_gas - selbstentl',
            "description": "Net storage level (recursive by day).",
        },
        {
            "column_name": "ladezust_abs_vorl_tl",
            "stage": "post",
            "order": 210,
            "expression": 'ladezust_brutto - COL_MIN("ladezust_brutto")',
            "description": "Absolute storage level before TL shift.",
        },
        {
            "column_name": "ladezust_absolute",
            "stage": "post",
            "order": 220,
            "expression": 'ladezust_netto - COL_MIN("ladezust_netto")',
            "description": "Absolute net storage level.",
        },
    ]

    WS365Formula.objects.bulk_create([WS365Formula(**row) for row in defaults], batch_size=100)


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0043_delete_wsformulatemplate_alter_formula_ws_row_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WS365Formula",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("column_name", models.CharField(help_text="Output column key used by WS API/Frontend (example: einspeich).", max_length=64, unique=True)),
                ("stage", models.CharField(choices=[("daily", "Daily (day-by-day 1-365)"), ("post", "Post (after full 365-day pass)")], default="daily", help_text="Daily runs during day loop; Post runs after all days are available.", max_length=16)),
                ("order", models.PositiveIntegerField(default=100, help_text="Execution order inside the selected stage.")),
                ("expression", models.TextField(help_text="Main expression. Helpers: IF, MIN, MAX, ABS, ROUND, PREV('column'). Post-stage also supports COL_MIN/COL_MAX/COL_SUM.")),
                ("day1_expression", models.TextField(blank=True, help_text="Optional day-1 override expression. Leave blank to use main expression.")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WS 365 Formula",
                "verbose_name_plural": "WS 365 Formulas",
                "ordering": ["stage", "order", "column_name"],
            },
        ),
        migrations.AddIndex(
            model_name="ws365formula",
            index=models.Index(fields=["is_active", "stage", "order"], name="simulator_w_is_acti_2150b0_idx"),
        ),
        migrations.RunPython(seed_default_ws365_formulas, migrations.RunPython.noop),
    ]
