# Generated by Django 4.2.24 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0044_ws365formula"),
    ]

    operations = [
        migrations.AddField(
            model_name="renewabledata",
            name="user_editable",
            field=models.BooleanField(default=False),
        ),
    ]

