# Generated by Django 4.2.24 on 2026-03-09 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0045_renewabledata_user_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'updated_at'], name='simulator_s_owner_i_717ddd_idx'), models.Index(fields=['name'], name='simulator_s_name_55edcc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scenariosnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='scenario_owner_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scenariosnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='scenario_global_name_uniq'),
        ),
    ]
