# Generated by Django 4.2.24 on 2026-03-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0048_alter_balancejob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='ws_row_type',
            field=models.CharField(blank=True, choices=[('all', 'All Rows (Default)'), ('day_1', 'Day 1 Only'), ('days_2_365', 'Days 2-365 (Pattern)'), ('annual_summary', 'Annual Summary (Legacy Slot)'), ('legacy_reference', 'Legacy Reference Slot'), ('row_368', 'Row 368+')], default='all', help_text=" FOR WS FORMULAS ONLY: Which rows this formula applies to. Use 'Days 2-365' for patterns with day_prev references.", max_length=20),
        ),
        migrations.AlterField(
            model_name='formulavariable',
            name='source_type',
            field=models.CharField(choices=[('landuse_status', 'LandUse status_ha'), ('landuse_target', 'LandUse target_ha'), ('renewable_status', 'RenewableData status_value (self)'), ('renewable_target', 'RenewableData target_value (self)'), ('renewable_code_status', ' Other RenewableData code - status'), ('renewable_code_target', ' Other RenewableData code - target'), ('verbrauch_status', 'VerbrauchData status (self)'), ('verbrauch_ziel', 'VerbrauchData ziel (self)'), ('verbrauch_code_status', ' Other VerbrauchData code - status'), ('verbrauch_code_ziel', ' Other VerbrauchData code - ziel'), ('ws_row_value', ' WSData current row column value'), ('ws_annual_summary', ' WS annual summary value'), ('ws_sum', ' WSData sum of column (days 1-365)'), ('ws_day_prev', ' WSData previous day column value'), ('literal', 'Literal number')], help_text='Type of data source', max_length=30),
        ),
    ]
