# Generated by Django 4.2.24 on 2026-04-22 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0049_alter_formula_ws_row_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64)),
                ('value_before', models.JSONField(blank=True, null=True)),
                ('value_after', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='user', help_text="'user' = direct edit; 'auto' = cascade-applied change", max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='simulator_m_owner_i_7bdb5c_idx'), models.Index(fields=['code'], name='simulator_m_code_f14d54_idx')],
            },
        ),
    ]
