# Generated by Django 4.2.24 on 2026-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0050_modificationhistoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebaeudewaermedata',
            name='notes_assumption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gebaeudewaermedata',
            name='origin',
            field=models.CharField(choices=[('d_xlsx', 'D.xlsx (Datenmodell)'), ('derived', 'Derived from d_xlsx parent'), ('internal', 'Internal (no Datenmodell counterpart)')], default='internal', max_length=16),
        ),
        migrations.AddField(
            model_name='gebaeudewaermedata',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landuse',
            name='notes_assumption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landuse',
            name='origin',
            field=models.CharField(choices=[('d_xlsx', 'D.xlsx (Datenmodell)'), ('derived', 'Derived from d_xlsx parent'), ('internal', 'Internal (no Datenmodell counterpart)')], default='internal', max_length=16),
        ),
        migrations.AddField(
            model_name='landuse',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='renewabledata',
            name='notes_assumption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewabledata',
            name='origin',
            field=models.CharField(choices=[('d_xlsx', 'D.xlsx (Datenmodell)'), ('derived', 'Derived from d_xlsx parent'), ('internal', 'Internal (no Datenmodell counterpart)')], default='internal', max_length=16),
        ),
        migrations.AddField(
            model_name='renewabledata',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='verbrauchdata',
            name='notes_assumption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verbrauchdata',
            name='origin',
            field=models.CharField(choices=[('d_xlsx', 'D.xlsx (Datenmodell)'), ('derived', 'Derived from d_xlsx parent'), ('internal', 'Internal (no Datenmodell counterpart)')], default='internal', max_length=16),
        ),
        migrations.AddField(
            model_name='verbrauchdata',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
