# Generated by Django 4.2.24 on 2026-04-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0055_wsdata_region_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wsdata',
            new_name='simulator_w_region__10066f_idx',
            old_name='simulator_w_region__40c1aa_idx',
        ),
    ]
