# Generated by Django 4.2.24 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0056_rename_simulator_w_region__40c1aa_idx_simulator_w_region__10066f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebaeudewaermedata",
            name="source_refs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="landuse",
            name="source_refs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="renewabledata",
            name="source_refs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="verbrauchdata",
            name="source_refs",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
