# Generated by Django 4.2.24 on 2026-05-19 14:23

from django.db import migrations, models
import django.db.models.deletion
import simulator.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0057_phase_a_source_refs_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIProvenanceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('landuse', 'Flächennutzung'), ('renewable', 'Erneuerbare Energien'), ('verbrauch', 'Verbrauch'), ('gebaeudewaerme', 'Gebäudewärme')], max_length=32)),
                ('row_code', models.CharField(max_length=50)),
                ('row_label', models.CharField(blank=True, max_length=255)),
                ('general_information', models.TextField(blank=True)),
                ('status_information', models.TextField(blank=True)),
                ('ziel_information', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(default=simulator.models.get_default_region_pk, on_delete=django.db.models.deletion.PROTECT, related_name='ui_provenance_overrides', to='simulator.region')),
            ],
            options={
                'verbose_name': 'UI Provenance Override',
                'verbose_name_plural': 'UI Provenance Overrides',
                'ordering': ['domain', 'row_code'],
            },
        ),
        migrations.CreateModel(
            name='UIProvenanceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('general', 'Allgemein'), ('status', 'Status'), ('ziel', 'Ziel')], default='general', max_length=16)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='simulator.uiprovenanceoverride')),
            ],
            options={
                'verbose_name': 'UI Provenance Source',
                'verbose_name_plural': 'UI Provenance Sources',
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='uiprovenanceoverride',
            index=models.Index(fields=['region', 'domain', 'row_code'], name='simulator_u_region__ccecb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='uiprovenanceoverride',
            constraint=models.UniqueConstraint(fields=('region', 'domain', 'row_code'), name='ui_provenance_override_region_domain_code_uniq'),
        ),
    ]
