# Generated by Django 4.2.24 on 2026-05-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simulator.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0058_uiprovenanceoverride_uiprovenancesource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('approved', 'Freigegeben'), ('archived', 'Archiviert')], default='draft', max_length=16)),
                ('is_protected', models.BooleanField(default=False, help_text='Protected versions cannot be deleted accidentally.')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_data_versions', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(default=simulator.models.get_default_region_pk, on_delete=django.db.models.deletion.PROTECT, related_name='admin_data_versions', to='simulator.region')),
            ],
            options={
                'verbose_name': 'Admin Data Version',
                'verbose_name_plural': 'Admin Data Versions',
                'ordering': ['-captured_at', '-updated_at'],
                'indexes': [models.Index(fields=['region', 'status'], name='simulator_a_region__2396bb_idx'), models.Index(fields=['captured_at'], name='simulator_a_capture_24277a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='admindataversion',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='admin_data_version_region_name_uniq'),
        ),
    ]
