# Generated by Django 4.2.24 on 2026-05-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0059_admindataversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admindataversion',
            options={'ordering': ['-captured_at', '-updated_at'], 'permissions': [('restore_admin_data_version', 'Can restore admin data versions'), ('refresh_admin_data_version', 'Can refresh admin data versions'), ('protect_admin_data_version', 'Can protect admin data versions')], 'verbose_name': 'Admin Data Version', 'verbose_name_plural': 'Admin Data Versions'},
        ),
    ]
