# Generated by Django 4.2.24 on 2026-06-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0063_scenario_snapshot_owner_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admindataversion',
            options={'ordering': ['-captured_at', '-updated_at'], 'permissions': [('restore_admin_data_version', 'Can restore admin data versions'), ('refresh_admin_data_version', 'Can refresh admin data versions'), ('protect_admin_data_version', 'Can protect admin data versions')], 'verbose_name': 'Datenmodell', 'verbose_name_plural': 'Datenmodelle'},
        ),
    ]
