"""
Django settings for landuse_project project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json
import logging
import os
import traceback
from datetime import datetime
from pathlib import Path

import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-q63gdi_*14rflq_y^l*3xxabvnz)kbla$9r=q@^8*7r8)s6r+t",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0,testserver"
    ).split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simulator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simulator.middleware.OwnerScopeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'landuse_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # §2.3 Phase B (T65): exposes active_regions +
                # active_region_code so the base.html nav dropdown
                # renders without per-view plumbing.
                'simulator.context_processors.region_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'landuse_project.wsgi.application'

USE_LOCAL_POSTGRES = os.environ.get("USE_LOCAL_POSTGRES", "False").lower() == "true"
DB_CONN_MAX_AGE = int(os.environ.get("DB_CONN_MAX_AGE", "600"))
DB_CONN_HEALTH_CHECKS = os.environ.get("DB_CONN_HEALTH_CHECKS", "true").lower() == "true"
DB_USE_PGBOUNCER = os.environ.get("DB_USE_PGBOUNCER", "false").lower() == "true"
DB_SSL_REQUIRE_ENV = os.environ.get("DJANGO_DB_SSL_REQUIRE")

def _env_bool(raw_value: str, default: bool = False) -> bool:
    if raw_value is None:
        return default
    return str(raw_value).strip().lower() in {"1", "true", "yes", "on"}

def _is_local_db_host(host_value: str) -> bool:
    host = (host_value or "").strip().lower()
    return host in {"", "localhost", "127.0.0.1", "db"}

if USE_LOCAL_POSTGRES:
    local_postgres_url = os.environ.get("LOCAL_POSTGRES_URL")
    if not local_postgres_url:
        raise RuntimeError(
            "USE_LOCAL_POSTGRES=true but LOCAL_POSTGRES_URL is missing."
        )

    local_db_config = dj_database_url.parse(
        local_postgres_url,
        conn_max_age=DB_CONN_MAX_AGE,
        ssl_require=False,
    )
    local_host = (local_db_config.get("HOST") or "").lower()
    allowed_local_hosts = {"", "localhost", "127.0.0.1"}
    if os.environ.get("ALLOW_DOCKER_POSTGRES_HOST", "false").lower() == "true":
        allowed_local_hosts.add("db")
    if local_host not in allowed_local_hosts:
        raise RuntimeError(
            "LOCAL_POSTGRES_URL must use localhost/127.0.0.1 in local mode."
            " Set ALLOW_DOCKER_POSTGRES_HOST=true to allow Docker host 'db'."
        )

    DATABASES = {"default": local_db_config}
else:
    if DB_SSL_REQUIRE_ENV is not None:
        db_ssl_require = _env_bool(DB_SSL_REQUIRE_ENV, default=not DEBUG)
    else:
        database_url_env = os.environ.get("DATABASE_URL")
        if database_url_env:
            try:
                parsed_env_db = dj_database_url.parse(
                    database_url_env,
                    conn_max_age=DB_CONN_MAX_AGE,
                    ssl_require=False,
                )
                db_ssl_require = not _is_local_db_host(parsed_env_db.get("HOST"))
            except Exception:
                db_ssl_require = not DEBUG
        else:
            db_ssl_require = not DEBUG

    DATABASES = {
        "default": dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=DB_CONN_MAX_AGE,
            ssl_require=db_ssl_require,
        )
    }

DATABASES["default"]["CONN_HEALTH_CHECKS"] = DB_CONN_HEALTH_CHECKS
if DB_USE_PGBOUNCER and DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True

# SQLite-only lock timeout tuning for localhost fallback.
if DATABASES["default"].get("ENGINE") == "django.db.backends.sqlite3":
    DATABASES["default"].setdefault("OPTIONS", {})["timeout"] = 60

# Cache: Redis when REDIS_URL is set (Heroku prod), otherwise local in-memory.
# Redis is required for the Step 1.4 bilanz cache to be shared across web/worker
# dynos. Local dev uses LocMemCache (single-process, still functional).
_REDIS_URL = os.environ.get("REDIS_URL")
if _REDIS_URL:
    # Heroku Redis uses self-signed TLS certs on rediss:// — Python's ssl
    # module rejects them by default. Disable cert verification (safe: the
    # connection itself is still encrypted; Heroku's internal network is
    # private). See https://devcenter.heroku.com/articles/connecting-heroku-redis
    _redis_options: dict = {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
        # Do NOT set IGNORE_EXCEPTIONS=True — it silently swallows errors
        # and returns None, which breaks the Step 1.4 cache-hit detection.
    }
    if _REDIS_URL.startswith("rediss://"):
        import ssl as _ssl
        _redis_options["CONNECTION_POOL_KWARGS"] = {
            "ssl_cert_reqs": _ssl.CERT_NONE,
        }
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _REDIS_URL,
            "OPTIONS": _redis_options,
        }
    }
else:
    CACHES = {
        "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True

# Per stakeholder PDF §2.5.2: German number format everywhere
# (dot for thousands grouping, comma as decimal separator).
# USE_L10N=True lets Django honour DECIMAL_SEPARATOR / THOUSAND_SEPARATOR
# in {% floatformat %} and related template filters using our custom
# formats (simulator/formats/de/formats.py overrides Django's default "de" locale).
USE_L10N = True
USE_THOUSAND_SEPARATOR = True
FORMAT_MODULE_PATH = ['simulator.formats']

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

WHITENOISE_ENABLED = os.environ.get("DJANGO_WHITENOISE_ENABLED", "true").lower() == "true"
if WHITENOISE_ENABLED:
    try:
        import whitenoise  # noqa: F401

        MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
        use_manifest_storage = (
            os.environ.get("DJANGO_STATICFILES_USE_MANIFEST", "").lower() == "true"
        )
        if not use_manifest_storage:
            use_manifest_storage = (not DEBUG) and (not USE_LOCAL_POSTGRES)

        if use_manifest_storage:
            STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
        else:
            STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
    except Exception:
        pass

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'simulator:login'
LOGIN_REDIRECT_URL = 'simulator:main_simulation'
LOGOUT_REDIRECT_URL = 'simulator:landing_page'

LANDUSE_MAX_INCREASE_PERCENT = 3  # Default: 3 percentage points increase only

LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").upper()

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "false").lower() == "true"
CSRF_COOKIE_SECURE = os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "false").lower() == "true"
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "false").lower() == "true"
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.environ.get("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "false").lower() == "true"
)
SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_SECURE_HSTS_PRELOAD", "false").lower() == "true"

class JsonFormatter(logging.Formatter):
    """JSON formatter for structured logs emitted to stdout."""

    def format(self, record):
        base = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "level": record.levelname.lower(),
            "component": record.name,
            "file": record.pathname,
            "line": record.lineno,
            "function": record.funcName,
            "message": record.getMessage(),
            "eventType": getattr(record, "eventType", "other"),
            "context": getattr(record, "context", {}),
            "stack": None,
        }

        if record.exc_info:
            base["stack"] = "".join(traceback.format_exception(*record.exc_info))

        return json.dumps(base, default=str)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "landuse_project.settings.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "simulator": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
        "calculation_engine": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",  # avoid per-query debug spam
            "propagate": False,
        },
    },
}
