"""Enumerate sheet structure of all Excel source files.

Writes:
  verification/formula_audit/00_source_inventory.md

For each .xlsx/.xlsm in docs/100prosim_d_*/:
  - sheet names
  - (max_row, max_col) for each sheet
  - named ranges defined at workbook level
  - approximate non-empty-cell count per sheet
"""
from __future__ import annotations
import os, sys, glob
from pathlib import Path
from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[3]
DOCS = ROOT / "docs"
OUT = ROOT / "verification" / "formula_audit" / "00_source_inventory.md"

def find_books():
    pat = str(DOCS / "100prosim_d_*" / "*.xls*")
    return sorted(glob.glob(pat))

def nonempty_count(ws):
    c = 0
    for row in ws.iter_rows(values_only=True):
        for v in row:
            if v is not None and v != "":
                c += 1
    return c

def dump_book(path: str, f):
    name = os.path.basename(path)
    size = os.path.getsize(path)
    f.write(f"\n## {name}  ({size:,} bytes)\n\n")
    try:
        wb = load_workbook(path, data_only=False, read_only=False, keep_links=False)
    except Exception as e:
        f.write(f"  ERROR: {e}\n")
        return

    # Named ranges
    defnames = list(wb.defined_names.keys()) if hasattr(wb, "defined_names") else []
    f.write(f"**Workbook-level named ranges ({len(defnames)})**:\n\n")
    if defnames:
        for dn in sorted(defnames):
            try:
                definition = wb.defined_names[dn]
                # attr_text gives formula-like reference, value gives resolved
                dest = getattr(definition, "attr_text", None) or str(definition.value)
            except Exception:
                dest = "<unreadable>"
            f.write(f"- `{dn}` → {dest}\n")
    else:
        f.write("- *(none)*\n")
    f.write("\n**Sheets**:\n\n")
    f.write("| sheet | max_row | max_col | non-empty cells |\n")
    f.write("|-------|--------:|--------:|----------------:|\n")
    for sn in wb.sheetnames:
        ws = wb[sn]
        try:
            ne = nonempty_count(ws)
        except Exception:
            ne = -1
        f.write(f"| {sn!r} | {ws.max_row} | {ws.max_column} | {ne} |\n")

def main():
    books = find_books()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Source Inventory (audit §0)\n\n")
        f.write(f"Enumerated {len(books)} workbooks from `docs/100prosim_d_*/`.\n")
        f.write(f"Generated by `verification/formula_audit/scripts/00_enumerate_sources.py`.\n")
        for p in books:
            dump_book(p, f)
    print(f"wrote {OUT}")
    print(f"{len(books)} books enumerated")

if __name__ == "__main__":
    main()
