"""Enumerate DB state (counts + sample) for the audit.

Writes: verification/formula_audit/00_db_inventory.md
Must run inside Docker (or with LOCAL_POSTGRES_URL + USE_LOCAL_POSTGRES=true).
"""
from __future__ import annotations
import os, sys, django
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "landuse_project.settings")
django.setup()

from simulator.models import (
    LandUse, VerbrauchData, RenewableData, GebaeudewaermeData, Formula
)
from simulator.ws_models import WSData

OUT = ROOT / "verification" / "formula_audit" / "00_db_inventory.md"

def q(model):
    return model.objects.all() if not hasattr(model, "all_objects") else model.all_objects.all()

def write_inventory():
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# DB Inventory (audit §0)\n\n")
        f.write("Row counts + sample of each table. Generated by `scripts/01_enumerate_db.py`.\n\n")

        for model in (LandUse, VerbrauchData, RenewableData, GebaeudewaermeData, Formula, WSData):
            rows = q(model)
            f.write(f"\n## `{model.__name__}` — {rows.count()} rows\n\n")
            if rows.count() == 0:
                continue
            fields = [fld.name for fld in model._meta.fields]
            f.write("Columns: `" + ", ".join(fields) + "`\n\n")
            # distinct owners
            if "owner" in fields:
                from django.contrib.auth import get_user_model
                owners = rows.values_list("owner__username", flat=True).distinct()
                f.write(f"Distinct owners ({len(owners)}): `{list(owners)[:10]}` ...\n\n")
            # per-owner count
            if "owner" in fields:
                from django.db.models import Count
                per = rows.values("owner__username").annotate(n=Count("id")).order_by("owner__username")
                f.write("Rows per owner:\n")
                for r in per:
                    f.write(f"  - {r['owner__username']}: {r['n']}\n")
                f.write("\n")
            # first 5 samples
            f.write("Sample (first 5):\n\n")
            for obj in rows[:5]:
                f.write(f"  - `{obj}`\n")

        # Formula breakdown by category/type
        f.write("\n## Formula breakdown\n\n")
        from collections import Counter
        rows = list(Formula.objects.values("category", "formula_type", "ws_row_type", "is_fixed"))
        cat = Counter(r["category"] for r in rows)
        ft = Counter(r["formula_type"] for r in rows)
        ws = Counter(r["ws_row_type"] for r in rows)
        fixed = Counter(r["is_fixed"] for r in rows)
        f.write("**By category** (top 30):\n")
        for k, v in cat.most_common(30):
            f.write(f"  - {k}: {v}\n")
        f.write("\n**By formula_type**:\n")
        for k, v in ft.most_common():
            f.write(f"  - {k}: {v}\n")
        f.write("\n**By ws_row_type** (top 20):\n")
        for k, v in ws.most_common(20):
            f.write(f"  - {k}: {v}\n")
        f.write("\n**By is_fixed**:\n")
        for k, v in fixed.most_common():
            f.write(f"  - {k}: {v}\n")
    print(f"wrote {OUT}")

if __name__ == "__main__":
    write_inventory()
